services:
  h-orchestra:
    build:
      context: .
      target: builder
    command: pnpm -r --parallel dev
    environment:
      MOUNT_PATH: /mounted-repo
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
      LOG_LEVEL: debug
    volumes:
      - ./packages/shared/src:/app/packages/shared/src
      - ./packages/backend/src:/app/packages/backend/src
      - ./packages/frontend/src:/app/packages/frontend/src
      - ./packages/frontend/index.html:/app/packages/frontend/index.html
    ports:
      - '3001:3001'
      - '5173:5173'
